#인증 방식 적용 완료 token
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-vs
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        exact: /kiali
    - uri:
        prefix: /kiali
    route:
    - destination:
        host: kiali.eshop.svc.cluster.local
        port:
          number: 20001
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kiali
  namespace: eshop
spec:
  host: kiali.eshop.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE